"""In-memory medication catalog for form autocomplete."""

from __future__ import annotations

from assistente_medico_api.schemas.medications import MedicationOption


def _entry(
    code: str,
    label: str,
    active_ingredient: str,
    source_tags: list[str],
) -> MedicationOption:
    return MedicationOption(
        code=code,
        label=label,
        activeIngredient=active_ingredient,
        sourceTags=source_tags,
    )


_MEDICATIONS: list[MedicationOption] = [
    _entry("ACIDO_ACETILSALICILICO", "Acido acetilsalicilico", "Acido acetilsalicilico", ["RENAME-2024"]),
    _entry("ACICLOVIR", "Aciclovir", "Aciclovir", ["RENAME-2024"]),
    _entry("ADALIMUMABE", "Adalimumabe", "Adalimumabe", ["CONITEC-PCDT"]),
    _entry("ALENDRONATO", "Alendronato de sodio", "Alendronato", ["RENAME-2024"]),
    _entry("AMITRIPTILINA", "Amitriptilina", "Amitriptilina", ["RENAME-2024"]),
    _entry("AMLODIPINO", "Amlodipino", "Amlodipino", ["RENAME-2024"]),
    _entry("AMOXICILINA", "Amoxicilina", "Amoxicilina", ["RENAME-2024"]),
    _entry(
        "AMOXICILINA_CLAVULANATO",
        "Amoxicilina + clavulanato",
        "Amoxicilina + acido clavulanico",
        ["RENAME-2024"],
    ),
    _entry("ATENOLOL", "Atenolol", "Atenolol", ["RENAME-2024"]),
    _entry("ATORVASTATINA", "Atorvastatina", "Atorvastatina", ["RENAME-2024"]),
    _entry("AZATIOPRINA", "Azatioprina", "Azatioprina", ["RENAME-2024", "CONITEC-PCDT"]),
    _entry("AZITROMICINA", "Azitromicina", "Azitromicina", ["RENAME-2024"]),
    _entry("BECLOMETASONA", "Beclometasona", "Beclometasona", ["RENAME-2024"]),
    _entry("BUDESONIDA", "Budesonida", "Budesonida", ["RENAME-2024", "CONITEC-PCDT"]),
    _entry("CAPTOPRIL", "Captopril", "Captopril", ["RENAME-2024"]),
    _entry("CARBONATO_CALCIO", "Carbonato de calcio", "Carbonato de calcio", ["RENAME-2024"]),
    _entry("CARVEDILOL", "Carvedilol", "Carvedilol", ["RENAME-2024"]),
    _entry("CEFALEXINA", "Cefalexina", "Cefalexina", ["RENAME-2024"]),
    _entry("CEFTRIAXONA", "Ceftriaxona", "Ceftriaxona", ["RENAME-2024"]),
    _entry("CICLOSPORINA", "Ciclosporina", "Ciclosporina", ["RENAME-2024", "CONITEC-PCDT"]),
    _entry("CIPROFLOXACINO", "Ciprofloxacino", "Ciprofloxacino", ["RENAME-2024"]),
    _entry("CLARITROMICINA", "Claritromicina", "Claritromicina", ["RENAME-2024"]),
    _entry("CLINDAMICINA", "Clindamicina", "Clindamicina", ["RENAME-2024"]),
    _entry("CLONAZEPAM", "Clonazepam", "Clonazepam", ["RENAME-2024"]),
    _entry("CLOPIDOGREL", "Clopidogrel", "Clopidogrel", ["RENAME-2024"]),
    _entry("COLECALCIFEROL", "Colecalciferol", "Vitamina D3", ["RENAME-2024"]),
    _entry("DIAZEPAM", "Diazepam", "Diazepam", ["RENAME-2024"]),
    _entry("DICLOFENACO", "Diclofenaco", "Diclofenaco", ["RENAME-2024"]),
    _entry("DIGOXINA", "Digoxina", "Digoxina", ["RENAME-2024"]),
    _entry("DIMENIDRINATO", "Dimenidrinato", "Dimenidrinato", ["RENAME-2024"]),
    _entry("DIPIRONA", "Dipirona", "Dipirona sodica", ["RENAME-2024"]),
    _entry("EMPAGLIFLOZINA", "Empagliflozina", "Empagliflozina", ["RENAME-2024", "CONITEC-PCDT"]),
    _entry("ENALAPRIL", "Enalapril", "Enalapril", ["RENAME-2024"]),
    _entry("ENOXAPARINA", "Enoxaparina", "Enoxaparina sodica", ["RENAME-2024"]),
    _entry("ESCITALOPRAM", "Escitalopram", "Escitalopram", ["RENAME-2024"]),
    _entry("ESPIRONOLACTONA", "Espironolactona", "Espironolactona", ["RENAME-2024"]),
    _entry("ETANERCEPTE", "Etanercepte", "Etanercepte", ["CONITEC-PCDT"]),
    _entry("FLUCONAZOL", "Fluconazol", "Fluconazol", ["RENAME-2024"]),
    _entry("FLUOXETINA", "Fluoxetina", "Fluoxetina", ["RENAME-2024"]),
    _entry("FUROSEMIDA", "Furosemida", "Furosemida", ["RENAME-2024"]),
    _entry("GLIBENCLAMIDA", "Glibenclamida", "Glibenclamida", ["RENAME-2024"]),
    _entry("GLICLAZIDA", "Gliclazida", "Gliclazida", ["RENAME-2024"]),
    _entry("HALOPERIDOL", "Haloperidol", "Haloperidol", ["RENAME-2024"]),
    _entry("HEPARINA_NAO_FRACIONADA", "Heparina nao fracionada", "Heparina sodica", ["RENAME-2024"]),
    _entry("HIDRALAZINA", "Hidralazina", "Hidralazina", ["RENAME-2024"]),
    _entry("HIDROCLOROTIAZIDA", "Hidroclorotiazida", "Hidroclorotiazida", ["RENAME-2024"]),
    _entry("HIDROCORTISONA", "Hidrocortisona", "Hidrocortisona", ["RENAME-2024"]),
    _entry("HIDROXICLOROQUINA", "Hidroxicloroquina", "Hidroxicloroquina", ["RENAME-2024", "CONITEC-PCDT"]),
    _entry("IBUPROFENO", "Ibuprofeno", "Ibuprofeno", ["RENAME-2024"]),
    _entry("INFLIXIMABE", "Infliximabe", "Infliximabe", ["CONITEC-PCDT"]),
    _entry("INSULINA_NPH", "Insulina humana NPH", "Insulina humana NPH", ["RENAME-2024"]),
    _entry("INSULINA_REGULAR", "Insulina humana regular", "Insulina humana regular", ["RENAME-2024"]),
    _entry("IPRATROPIO", "Brometo de ipratropio", "Brometo de ipratropio", ["RENAME-2024"]),
    _entry("LEFLUNOMIDA", "Leflunomida", "Leflunomida", ["RENAME-2024", "CONITEC-PCDT"]),
    _entry("LEVOFLOXACINO", "Levofloxacino", "Levofloxacino", ["RENAME-2024"]),
    _entry("LEVOTIROXINA", "Levotiroxina sodica", "Levotiroxina sodica", ["RENAME-2024"]),
    _entry("LOSARTANA", "Losartana", "Losartana potassica", ["RENAME-2024"]),
    _entry("MESALAZINA", "Mesalazina", "Mesalazina", ["RENAME-2024", "CONITEC-PCDT"]),
    _entry("METFORMINA", "Metformina", "Metformina", ["RENAME-2024"]),
    _entry("METOCLOPRAMIDA", "Metoclopramida", "Metoclopramida", ["RENAME-2024"]),
    _entry("METOPROLOL", "Metoprolol", "Metoprolol", ["RENAME-2024"]),
    _entry("METOTREXATO", "Metotrexato", "Metotrexato", ["RENAME-2024", "CONITEC-PCDT"]),
    _entry("METRONIDAZOL", "Metronidazol", "Metronidazol", ["RENAME-2024"]),
    _entry("MORFINA", "Morfina", "Morfina", ["RENAME-2024"]),
    _entry("NAPROXENO", "Naproxeno", "Naproxeno", ["RENAME-2024"]),
    _entry("NIFEDIPINO", "Nifedipino", "Nifedipino", ["RENAME-2024"]),
    _entry("NITROFURANTOINA", "Nitrofurantoina", "Nitrofurantoina", ["RENAME-2024"]),
    _entry("OMEPRAZOL", "Omeprazol", "Omeprazol", ["RENAME-2024"]),
    _entry("ONDANSETRONA", "Ondansetrona", "Ondansetrona", ["RENAME-2024"]),
    _entry("OSELTAMIVIR", "Oseltamivir", "Oseltamivir", ["RENAME-2024"]),
    _entry("PANTOPRAZOL", "Pantoprazol", "Pantoprazol", ["RENAME-2024"]),
    _entry("PARACETAMOL", "Paracetamol", "Paracetamol", ["RENAME-2024"]),
    _entry("PREDNISOLONA", "Prednisolona", "Prednisolona", ["RENAME-2024"]),
    _entry("PREDNISONA", "Prednisona", "Prednisona", ["RENAME-2024"]),
    _entry("QUETIAPINA", "Quetiapina", "Quetiapina", ["RENAME-2024"]),
    _entry("RISPERIDONA", "Risperidona", "Risperidona", ["RENAME-2024"]),
    _entry("SALBUTAMOL", "Salbutamol", "Salbutamol", ["RENAME-2024"]),
    _entry("SECUQUINUMABE", "Secuquinumabe", "Secuquinumabe", ["CONITEC-PCDT"]),
    _entry("SERTRALINA", "Sertralina", "Sertralina", ["RENAME-2024"]),
    _entry("SINVASTATINA", "Sinvastatina", "Sinvastatina", ["RENAME-2024"]),
    _entry("SULFAMETOXAZOL_TRIMETOPRIMA", "Sulfametoxazol + trimetoprima", "Sulfametoxazol + trimetoprima", ["RENAME-2024"]),
    _entry("SULFASSALAZINA", "Sulfassalazina", "Sulfassalazina", ["RENAME-2024", "CONITEC-PCDT"]),
    _entry("SULFATO_FERROSO", "Sulfato ferroso", "Sulfato ferroso", ["RENAME-2024"]),
    _entry("TOCILIZUMABE", "Tocilizumabe", "Tocilizumabe", ["CONITEC-PCDT"]),
    _entry("TOFACITINIBE", "Tofacitinibe", "Tofacitinibe", ["CONITEC-PCDT"]),
    _entry("TRAMADOL", "Tramadol", "Tramadol", ["RENAME-2024"]),
    _entry("USTEQUINUMABE", "Ustequinumabe", "Ustequinumabe", ["CONITEC-PCDT"]),
    _entry("VARFARINA", "Varfarina", "Varfarina sodica", ["RENAME-2024"]),
]

MEDICATION_LIST: list[MedicationOption] = sorted(
    _MEDICATIONS,
    key=lambda med: med.label.lower(),
)


def list_medications() -> list[MedicationOption]:
    return MEDICATION_LIST
