"""In-memory medication catalog for form autocomplete."""

from __future__ import annotations

from assistente_medico_api.schemas.medications import MedicationOption


def _entry(
    code: str,
    label: str,
    active_ingredient: str,
    source_tags: list[str],
) -> MedicationOption:
    return MedicationOption(
        code=code,
        label=label,
        activeIngredient=active_ingredient,
        sourceTags=source_tags,
    )


_MEDICATIONS: list[MedicationOption] = [
    _entry("ABATACEPTE", "Abatacepte", "Abatacepte", ["RENAME-2024"]),
    _entry("ABCIXIMABE", "Abciximabe", "Abciximabe", ["RENAME-2024"]),
    _entry("ACETATO_DE_BETAMETASONA_MAIS_FOSFATO_DISSODICO_DE_BETAMETASONA", "Acetato de betametasona + fosfato dissodico de betametasona", "Acetato de betametasona + fosfato dissodico de betametasona", ["RENAME-2024"]),
    _entry("ACETATO_DE_CIPROTERONA", "Acetato de ciproterona", "Acetato de ciproterona", ["RENAME-2024"]),
    _entry("ACETATO_DE_DESMOPRESSINA", "Acetato de desmopressina", "Acetato de desmopressina", ["RENAME-2024"]),
    _entry("ACETATO_DE_FLUDROCORTISONA", "Acetato de fludrocortisona", "Acetato de fludrocortisona", ["RENAME-2024"]),
    _entry("ACETATO_DE_GLATIRAMER", "Acetato de glatiramer", "Acetato de glatiramer", ["RENAME-2024"]),
    _entry("ACETATO_DE_GOSSERRELINA", "Acetato de gosserrelina", "Acetato de gosserrelina", ["RENAME-2024"]),
    _entry("ACETATO_DE_HIDROCORTISONA", "Acetato de hidrocortisona", "Acetato de hidrocortisona", ["RENAME-2024"]),
    _entry("ACETATO_DE_LANREOTIDA", "Acetato de lanreotida", "Acetato de lanreotida", ["RENAME-2024"]),
    _entry("ACETATO_DE_LEUPRORRELINA", "Acetato de leuprorrelina", "Acetato de leuprorrelina", ["RENAME-2024"]),
    _entry("ACETATO_DE_MEDROXIPROGESTERONA", "Acetato de medroxiprogesterona", "Acetato de medroxiprogesterona", ["RENAME-2024"]),
    _entry("ACETATO_DE_MEDROXIPROGESTERONA_MAIS_CIPIONATO_DE_ESTRADIOL", "Acetato de medroxiprogesterona + cipionato de estradiol", "Acetato de medroxiprogesterona + cipionato de estradiol", ["RENAME-2024"]),
    _entry("ACETATO_DE_OCTREOTIDA", "Acetato de octreotida", "Acetato de octreotida", ["RENAME-2024"]),
    _entry("ACETATO_DE_SODIO", "Acetato de sodio", "Acetato de sodio", ["RENAME-2024"]),
    _entry("ACETAZOLAMIDA", "Acetazolamida", "Acetazolamida", ["RENAME-2024"]),
    _entry("ACICLOVIR", "Aciclovir", "Aciclovir", ["RENAME-2024"]),
    _entry("ACIDO_ACETILSALICILICO", "Acido acetilsalicilico", "Acido acetilsalicilico", ["RENAME-2024"]),
    _entry("ACIDO_FOLICO", "Acido folico", "Acido folico", ["RENAME-2024"]),
    _entry("ACIDO_FOLINICO", "Acido folinico", "Acido folinico", ["RENAME-2024"]),
    _entry("ACIDO_NICOTINICO", "Acido nicotinico", "Acido nicotinico", ["RENAME-2024"]),
    _entry("ACIDO_PARAMINOSSALICILICO", "Acido paraminossalicilico", "Acido paraminossalicilico", ["RENAME-2024"]),
    _entry("ACIDO_SALICILICO_FN", "Acido salicilico (FN)", "Acido salicilico (FN)", ["RENAME-2024"]),
    _entry("ACIDO_TRANEXAMICO", "Acido tranexamico", "Acido tranexamico", ["RENAME-2024"]),
    _entry("ACIDO_URSODESOXICOLICO", "Acido ursodesoxicolico", "Acido ursodesoxicolico", ["RENAME-2024"]),
    _entry("ACIDO_VALPROICO", "Acido valproico", "Acido valproico", ["RENAME-2024"]),
    _entry("ACIDO_ZOLEDRONICO", "Acido zoledronico", "Acido zoledronico", ["RENAME-2024"]),
    _entry("ACITRETINA", "Acitretina", "Acitretina", ["RENAME-2024"]),
    _entry("ADALIMUMABE", "Adalimumabe", "Adalimumabe", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("AGUA_PARA_INJETAVEIS", "Agua para injetaveis", "Agua para injetaveis", ["RENAME-2024"]),
    _entry("ALBENDAZOL", "Albendazol", "Albendazol", ["RENAME-2024"]),
    _entry("ALBUMINA_HUMANA", "Albumina humana", "Albumina humana", ["RENAME-2024"]),
    _entry("ALCATRAO_MINERAL_FN", "Alcatrao mineral (FN)", "Alcatrao mineral (FN)", ["RENAME-2024"]),
    _entry("ALCOOL_ETILICO_FN", "Alcool etilico (FN)", "Alcool etilico (FN)", ["RENAME-2024"]),
    _entry("ALENDRONATO", "Alendronato de sodio", "Alendronato", ["RENAME-2024"]),
    _entry("ALENTUZUMABE", "Alentuzumabe", "Alentuzumabe", ["RENAME-2024"]),
    _entry("ALFA_AGALSIDASE", "Alfa-agalsidase", "Alfa-agalsidase", ["RENAME-2024"]),
    _entry("ALFA_ALGLICOSIDADE", "Alfa-alglicosidade", "Alfa-alglicosidade", ["RENAME-2024"]),
    _entry("ALFACERLIPONASE", "Alfacerliponase", "Alfacerliponase", ["RENAME-2024"]),
    _entry("ALFADORNASE", "Alfadornase", "Alfadornase", ["RENAME-2024"]),
    _entry("ALFAELOSULFASE", "Alfaelosulfase", "Alfaelosulfase", ["RENAME-2024"]),
    _entry("ALFAEPOETINA", "Alfaepoetina", "Alfaepoetina", ["RENAME-2024"]),
    _entry("ALFAINTERFERONA_2B", "Alfainterferona 2b", "Alfainterferona 2b", ["RENAME-2024"]),
    _entry("ALFAPEGINTERFERONA_2A", "Alfapeginterferona 2a", "Alfapeginterferona 2a", ["RENAME-2024"]),
    _entry("ALFAPEGINTERFERONA_2B", "Alfapeginterferona 2b", "Alfapeginterferona 2b", ["RENAME-2024"]),
    _entry("ALFAPORACTANTO_SURFACTANTE_PULMONAR", "Alfaporactanto (surfactante pulmonar)", "Alfaporactanto (surfactante pulmonar)", ["RENAME-2024"]),
    _entry("ALFATALIGLICERASE", "Alfataliglicerase", "Alfataliglicerase", ["RENAME-2024"]),
    _entry("ALFAVELAGLICERASE", "Alfavelaglicerase", "Alfavelaglicerase", ["RENAME-2024"]),
    _entry("ALFAVESTRONIDASE", "Alfavestronidase", "Alfavestronidase", ["RENAME-2024"]),
    _entry("ALGESTONA_ACETOFENIDA_MAIS_ENANTATO_DE_ESTRADIOL", "Algestona acetofenida + enantato de estradiol", "Algestona acetofenida + enantato de estradiol", ["RENAME-2024"]),
    _entry("ALOPURINOL", "Alopurinol", "Alopurinol", ["RENAME-2024"]),
    _entry("ALTEPLASE", "Alteplase", "Alteplase", ["RENAME-2024"]),
    _entry("AMBRISENTANA", "Ambrisentana", "Ambrisentana", ["RENAME-2024"]),
    _entry("AMITRIPTILINA", "Amitriptilina", "Amitriptilina", ["RENAME-2024"]),
    _entry("AMLODIPINO", "Amlodipino", "Amlodipino", ["RENAME-2024"]),
    _entry("AMOXICILINA", "Amoxicilina", "Amoxicilina", ["RENAME-2024"]),
    _entry("AMOXICILINA_CLAVULANATO", "Amoxicilina + clavulanato", "Amoxicilina + acido clavulanico", ["RENAME-2024"]),
    _entry("AMOXICILINA_MAIS_CLAVULANATO_DE_POTASSIO", "Amoxicilina + clavulanato de potassio", "Amoxicilina + clavulanato de potassio", ["RENAME-2024"]),
    _entry("ANFOTERICINA_B_COMPLEXO_LIPIDICO", "Anfotericina B (complexo lipidico)", "Anfotericina B (complexo lipidico)", ["RENAME-2024"]),
    _entry("ANFOTERICINA_B_DESOXICOLATO", "Anfotericina B (desoxicolato)", "Anfotericina B (desoxicolato)", ["RENAME-2024"]),
    _entry("ANFOTERICINA_B_LIPOSSOMAL", "Anfotericina B (lipossomal)", "Anfotericina B (lipossomal)", ["RENAME-2024"]),
    _entry("ANIDULAFUNGINA", "Anidulafungina", "Anidulafungina", ["RENAME-2024"]),
    _entry("ANTIMONIATO_DE_MEGLUMINA", "Antimoniato de meglumina", "Antimoniato de meglumina", ["RENAME-2024"]),
    _entry("ARTEMETER_MAIS_LUMEFANTRINA", "Artemeter + lumefantrina", "Artemeter + lumefantrina", ["RENAME-2024"]),
    _entry("ARTESUNATO", "Artesunato", "Artesunato", ["RENAME-2024"]),
    _entry("ARTESUNATO_MAIS_MEFLOQUINA", "Artesunato + mefloquina", "Artesunato + mefloquina", ["RENAME-2024"]),
    _entry("ATENOLOL", "Atenolol", "Atenolol", ["RENAME-2024"]),
    _entry("ATORVASTATINA", "Atorvastatina", "Atorvastatina", ["RENAME-2024"]),
    _entry("ATORVASTATINA_CALCICA", "Atorvastatina calcica", "Atorvastatina calcica", ["RENAME-2024"]),
    _entry("AZATIOPRINA", "Azatioprina", "Azatioprina", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("AZITROMICINA", "Azitromicina", "Azitromicina", ["RENAME-2024"]),
    _entry("BARICITINIBE", "Baricitinibe", "Baricitinibe", ["RENAME-2024"]),
    _entry("BASILIXIMABE", "Basiliximabe", "Basiliximabe", ["RENAME-2024"]),
    _entry("BECLOMETASONA", "Beclometasona", "Beclometasona", ["RENAME-2024"]),
    _entry("BEDAQUILINA", "Bedaquilina", "Bedaquilina", ["RENAME-2024"]),
    _entry("BENZILPENICILINA_BENZATINA", "Benzilpenicilina benzatina", "Benzilpenicilina benzatina", ["RENAME-2024"]),
    _entry("BENZILPENICILINA_POTASSICA", "Benzilpenicilina potassica", "Benzilpenicilina potassica", ["RENAME-2024"]),
    _entry("BENZILPENICILINA_PROCAINA_MAIS_BENZILPENICILINA_POTASSICA", "Benzilpenicilina procaina + benzilpenicilina potassica", "Benzilpenicilina procaina + benzilpenicilina potassica", ["RENAME-2024"]),
    _entry("BENZNIDAZOL", "Benznidazol", "Benznidazol", ["RENAME-2024"]),
    _entry("BENZOILMETRONIDAZOL", "Benzoilmetronidazol", "Benzoilmetronidazol", ["RENAME-2024"]),
    _entry("BERACTANTO_SURFACTANTE_PULMONAR", "Beractanto (surfactante pulmonar)", "Beractanto (surfactante pulmonar)", ["RENAME-2024"]),
    _entry("BESILATO_DE_ANLODIPINO", "Besilato de anlodipino", "Besilato de anlodipino", ["RENAME-2024"]),
    _entry("BETA_AGALSIDASE", "Beta-agalsidase", "Beta-agalsidase", ["RENAME-2024"]),
    _entry("BETAINTERFERONA_1A", "Betainterferona 1a", "Betainterferona 1a", ["RENAME-2024"]),
    _entry("BETAINTERFERONA_1B", "Betainterferona 1b", "Betainterferona 1b", ["RENAME-2024"]),
    _entry("BEZAFIBRATO", "Bezafibrato", "Bezafibrato", ["RENAME-2024"]),
    _entry("BICARBONATO_DE_SODIO", "Bicarbonato de sodio", "Bicarbonato de sodio", ["RENAME-2024"]),
    _entry("BIMATOPROSTA", "Bimatoprosta", "Bimatoprosta", ["RENAME-2024"]),
    _entry("BIOTINA", "Biotina", "Biotina", ["RENAME-2024"]),
    _entry("BISSULFATO_DE_CLOPIDOGREL", "Bissulfato de clopidogrel", "Bissulfato de clopidogrel", ["RENAME-2024"]),
    _entry("BOSENTANA", "Bosentana", "Bosentana", ["RENAME-2024"]),
    _entry("BRINZOLAMIDA", "Brinzolamida", "Brinzolamida", ["RENAME-2024"]),
    _entry("IPRATROPIO", "Brometo de ipratropio", "Brometo de ipratropio", ["RENAME-2024"]),
    _entry("BROMETO_DE_PIRIDOSTIGMINA", "Brometo de piridostigmina", "Brometo de piridostigmina", ["RENAME-2024"]),
    _entry("BROMETO_DE_TIOTROPIO_MONOIDRATADO_MAIS_CLORIDRATO_DE_OLODATEROL", "Brometo de tiotropio monoidratado + cloridrato de olodaterol", "Brometo de tiotropio monoidratado + cloridrato de olodaterol", ["RENAME-2024"]),
    _entry("BROMETO_DE_UMECLIDINIO_MAIS_TRIFENATATO_DE_VILANTEROL", "Brometo de umeclidinio + trifenatato de vilanterol", "Brometo de umeclidinio + trifenatato de vilanterol", ["RENAME-2024"]),
    _entry("BROMIDRATO_DE_FENOTEROL", "Bromidrato de fenoterol", "Bromidrato de fenoterol", ["RENAME-2024"]),
    _entry("BROMIDRATO_DE_GALANTAMINA", "Bromidrato de galantamina", "Bromidrato de galantamina", ["RENAME-2024"]),
    _entry("BUDESONIDA", "Budesonida", "Budesonida", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("BUROSUMABE", "Burosumabe", "Burosumabe", ["RENAME-2024"]),
    _entry("CABERGOLINA", "Cabergolina", "Cabergolina", ["RENAME-2024"]),
    _entry("CALCIPOTRIOL", "Calcipotriol", "Calcipotriol", ["RENAME-2024"]),
    _entry("CALCITONINA", "Calcitonina", "Calcitonina", ["RENAME-2024"]),
    _entry("CALCITRIOL", "Calcitriol", "Calcitriol", ["RENAME-2024"]),
    _entry("CAPREOMICINA", "Capreomicina", "Capreomicina", ["RENAME-2024"]),
    _entry("CAPTOPRIL", "Captopril", "Captopril", ["RENAME-2024"]),
    _entry("CARBAMAZEPINA", "Carbamazepina", "Carbamazepina", ["RENAME-2024"]),
    _entry("CARBONATO_CALCIO", "Carbonato de calcio", "Carbonato de calcio", ["RENAME-2024"]),
    _entry("CARBONATO_DE_CALCIO_MAIS_COLECALCIFEROL", "Carbonato de calcio + colecalciferol", "Carbonato de calcio + colecalciferol", ["RENAME-2024"]),
    _entry("CARBONATO_DE_LITIO", "Carbonato de litio", "Carbonato de litio", ["RENAME-2024"]),
    _entry("CARVAO_VEGETAL_ATIVADO", "Carvao vegetal ativado", "Carvao vegetal ativado", ["RENAME-2024"]),
    _entry("CARVEDILOL", "Carvedilol", "Carvedilol", ["RENAME-2024"]),
    _entry("CEFALEXINA", "Cefalexina", "Cefalexina", ["RENAME-2024"]),
    _entry("CEFOTAXIMA_SODICA", "Cefotaxima sodica", "Cefotaxima sodica", ["RENAME-2024"]),
    _entry("CEFTRIAXONA", "Ceftriaxona", "Ceftriaxona", ["RENAME-2024"]),
    _entry("CERTOLIZUMABE_PEGOL", "Certolizumabe pegol", "Certolizumabe pegol", ["RENAME-2024"]),
    _entry("CETOCONAZOL", "Cetoconazol", "Cetoconazol", ["RENAME-2024"]),
    _entry("CIANOCOBALAMINA", "Cianocobalamina", "Cianocobalamina", ["RENAME-2024"]),
    _entry("CICLOFOSFAMIDA", "Ciclofosfamida", "Ciclofosfamida", ["RENAME-2024"]),
    _entry("CICLOSPORINA", "Ciclosporina", "Ciclosporina", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("CIPROFIBRATO", "Ciprofibrato", "Ciprofibrato", ["RENAME-2024"]),
    _entry("CIPROFLOXACINO", "Ciprofloxacino", "Ciprofloxacino", ["RENAME-2024"]),
    _entry("CITRATO_DE_DIETILCARBAMAZINA", "Citrato de dietilcarbamazina", "Citrato de dietilcarbamazina", ["RENAME-2024"]),
    _entry("CITRATO_DE_SILDENAFILA", "Citrato de sildenafila", "Citrato de sildenafila", ["RENAME-2024"]),
    _entry("CLADRIBINA", "Cladribina", "Cladribina", ["RENAME-2024"]),
    _entry("CLARITROMICINA", "Claritromicina", "Claritromicina", ["RENAME-2024"]),
    _entry("CLINDAMICINA", "Clindamicina", "Clindamicina", ["RENAME-2024"]),
    _entry("CLOBAZAM", "Clobazam", "Clobazam", ["RENAME-2024"]),
    _entry("CLONAZEPAM", "Clonazepam", "Clonazepam", ["RENAME-2024"]),
    _entry("CLOPIDOGREL", "Clopidogrel", "Clopidogrel", ["RENAME-2024"]),
    _entry("CLORANFENICOL", "Cloranfenicol", "Cloranfenicol", ["RENAME-2024"]),
    _entry("CLORETO_DE_POTASSIO", "Cloreto de potassio", "Cloreto de potassio", ["RENAME-2024"]),
    _entry("CLORETO_DE_SODIO", "Cloreto de sodio", "Cloreto de sodio", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_AMANTADINA", "Cloridrato de amantadina", "Cloridrato de amantadina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_AMIODARONA", "Cloridrato de amiodarona", "Cloridrato de amiodarona", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_AMITRIPTILINA", "Cloridrato de amitriptilina", "Cloridrato de amitriptilina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_BIPERIDENO", "Cloridrato de biperideno", "Cloridrato de biperideno", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_BUPIVACAINA", "Cloridrato de bupivacaina", "Cloridrato de bupivacaina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_BUPROPIONA", "Cloridrato de bupropiona", "Cloridrato de bupropiona", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_CINACALCETE", "Cloridrato de cinacalcete", "Cloridrato de cinacalcete", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_CLINDAMICINA", "Cloridrato de clindamicina", "Cloridrato de clindamicina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_CLOMIPRAMINA", "Cloridrato de clomipramina", "Cloridrato de clomipramina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_CLORPROMAZINA", "Cloridrato de clorpromazina", "Cloridrato de clorpromazina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_DOBUTAMINA", "Cloridrato de dobutamina", "Cloridrato de dobutamina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_DONEPEZILA", "Cloridrato de donepezila", "Cloridrato de donepezila", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_DOPAMINA", "Cloridrato de dopamina", "Cloridrato de dopamina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_DORZOLAMIDA", "Cloridrato de dorzolamida", "Cloridrato de dorzolamida", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_ETAMBUTOL", "Cloridrato de etambutol", "Cloridrato de etambutol", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_FINGOLIMODE", "Cloridrato de fingolimode", "Cloridrato de fingolimode", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_FLUOXETINA", "Cloridrato de fluoxetina", "Cloridrato de fluoxetina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_HIDRALAZINA", "Cloridrato de hidralazina", "Cloridrato de hidralazina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_HIDROXOCOBALAMINA", "Cloridrato de hidroxocobalamina", "Cloridrato de hidroxocobalamina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_LIDOCAINA", "Cloridrato de lidocaina", "Cloridrato de lidocaina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_LIDOCAINA_MAIS_GLICOSE", "Cloridrato de lidocaina + glicose", "Cloridrato de lidocaina + glicose", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_LIDOCAINA_MAIS_HEMITARTARATO_DE_EPINEFRINA", "Cloridrato de lidocaina + hemitartarato de epinefrina", "Cloridrato de lidocaina + hemitartarato de epinefrina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_MEMANTINA", "Cloridrato de memantina", "Cloridrato de memantina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_METADONA", "Cloridrato de metadona", "Cloridrato de metadona", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_METFORMINA", "Cloridrato de metformina", "Cloridrato de metformina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_METOCLOPRAMIDA", "Cloridrato de metoclopramida", "Cloridrato de metoclopramida", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_MINOCICLINA", "Cloridrato de minociclina", "Cloridrato de minociclina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_MOXIFLOXACINO", "Cloridrato de moxifloxacino", "Cloridrato de moxifloxacino", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_NALOXONA", "Cloridrato de naloxona", "Cloridrato de naloxona", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_NORTRIPTILINA", "Cloridrato de nortriptilina", "Cloridrato de nortriptilina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_ONDANSETRONA", "Cloridrato de ondansetrona", "Cloridrato de ondansetrona", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_PILOCARPINA", "Cloridrato de pilocarpina", "Cloridrato de pilocarpina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_PIRIDOXINA", "Cloridrato de piridoxina", "Cloridrato de piridoxina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_PRILOCAINA_MAIS_FELIPRESSINA", "Cloridrato de prilocaina + felipressina", "Cloridrato de prilocaina + felipressina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_PROMETAZINA", "Cloridrato de prometazina", "Cloridrato de prometazina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_PROPAFENONA", "Cloridrato de propafenona", "Cloridrato de propafenona", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_PROPRANOLOL", "Cloridrato de propranolol", "Cloridrato de propranolol", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_PROTAMINA", "Cloridrato de protamina", "Cloridrato de protamina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_RALOXIFENO", "Cloridrato de raloxifeno", "Cloridrato de raloxifeno", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_SELEGILINA", "Cloridrato de selegilina", "Cloridrato de selegilina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_SEVELAMER", "Cloridrato de sevelamer", "Cloridrato de sevelamer", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_TETRACICLINA", "Cloridrato de tetraciclina", "Cloridrato de tetraciclina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_TIAMINA", "Cloridrato de tiamina", "Cloridrato de tiamina", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_TIROFIBANA", "Cloridrato de tirofibana", "Cloridrato de tirofibana", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_TRIEXIFENIDIL", "Cloridrato de triexifenidil", "Cloridrato de triexifenidil", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_VERAPAMIL", "Cloridrato de verapamil", "Cloridrato de verapamil", ["RENAME-2024"]),
    _entry("CLORIDRATO_DE_ZIPRASIDONA", "Cloridrato de ziprasidona", "Cloridrato de ziprasidona", ["RENAME-2024"]),
    _entry("CLOZAPINA", "Clozapina", "Clozapina", ["RENAME-2024"]),
    _entry("COLECALCIFEROL", "Colecalciferol", "Vitamina D3", ["RENAME-2024"]),
    _entry("COLISTIMETATO_DE_SODIO", "Colistimetato de sodio", "Colistimetato de sodio", ["RENAME-2024"]),
    _entry("COMPLEMENTO_ALIMENTAR_PARA_PACIENTE_FENILCETONURICO_MAIOR_DE_1_ANO_FORMULA_DE_AMINOACIDOS_ISENTA_DE_FENILALANINA", "Complemento alimentar para paciente fenilcetonurico maior de 1 ano (formula de aminoacidos isenta de fenilalanina)", "Complemento alimentar para paciente fenilcetonurico maior de 1 ano (formula de aminoacidos isenta de fenilalanina)", ["RENAME-2024"]),
    _entry("COMPLEMENTO_ALIMENTAR_PARA_PACIENTE_FENILCETONURICO_MENOR_DE_1_ANO_FORMULA_DE_AMINOACIDOS_ISENTA_DE_FENILALANINA", "Complemento alimentar para paciente fenilcetonurico menor de 1 ano (formula de aminoacidos isenta de fenilalanina)", "Complemento alimentar para paciente fenilcetonurico menor de 1 ano (formula de aminoacidos isenta de fenilalanina)", ["RENAME-2024"]),
    _entry("COMPLEXO_PROTROMBINICO_HUMANO", "Complexo protrombinico humano", "Complexo protrombinico humano", ["RENAME-2024"]),
    _entry("COMPLEXO_PROTROMBINICO_PARCIALMENTE_ATIVADO", "Complexo protrombinico parcialmente ativado", "Complexo protrombinico parcialmente ativado", ["RENAME-2024"]),
    _entry("DACLATASVIR", "Daclatasvir", "Daclatasvir", ["RENAME-2024"]),
    _entry("DACLIZUMABE", "Daclizumabe", "Daclizumabe", ["RENAME-2024"]),
    _entry("DANAZOL", "Danazol", "Danazol", ["RENAME-2024"]),
    _entry("DAPAGLIFLOZINA_PROPANODIOL", "Dapagliflozina propanodiol", "Dapagliflozina propanodiol", ["RENAME-2024"]),
    _entry("DARUNAVIR", "Darunavir", "Darunavir", ["RENAME-2024"]),
    _entry("DEFERASIROX", "Deferasirox", "Deferasirox", ["RENAME-2024"]),
    _entry("DEFERIPRONA", "Deferiprona", "Deferiprona", ["RENAME-2024"]),
    _entry("DELAMANIDA", "Delamanida", "Delamanida", ["RENAME-2024"]),
    _entry("DEXAMETASONA", "Dexametasona", "Dexametasona", ["RENAME-2024"]),
    _entry("DIAZEPAM", "Diazepam", "Diazepam", ["RENAME-2024"]),
    _entry("DICLOFENACO", "Diclofenaco", "Diclofenaco", ["RENAME-2024"]),
    _entry("DICLORIDRATO_DE_PRAMIPEXOL", "Dicloridrato de pramipexol", "Dicloridrato de pramipexol", ["RENAME-2024"]),
    _entry("DICLORIDRATO_DE_SAPROPTERINA", "Dicloridrato de sapropterina", "Dicloridrato de sapropterina", ["RENAME-2024"]),
    _entry("DICLORIDRATO_DE_TRIENTINA", "Dicloridrato de trientina", "Dicloridrato de trientina", ["RENAME-2024"]),
    _entry("DIFOSFATO_DE_CLOROQUINA", "Difosfato de cloroquina", "Difosfato de cloroquina", ["RENAME-2024"]),
    _entry("DIFOSFATO_DE_PRIMAQUINA", "Difosfato de primaquina", "Difosfato de primaquina", ["RENAME-2024"]),
    _entry("DIGLICONATO_DE_CLOREXIDINA", "Digliconato de clorexidina", "Digliconato de clorexidina", ["RENAME-2024"]),
    _entry("DIGOXINA", "Digoxina", "Digoxina", ["RENAME-2024"]),
    _entry("DIMENIDRINATO", "Dimenidrinato", "Dimenidrinato", ["RENAME-2024"]),
    _entry("DINITRATO_DE_ISOSSORBIDA", "Dinitrato de isossorbida", "Dinitrato de isossorbida", ["RENAME-2024"]),
    _entry("DIPIRONA", "Dipirona", "Dipirona sodica", ["RENAME-2024"]),
    _entry("DIPROPIONATO_DE_BECLOMETASONA", "Dipropionato de beclometasona", "Dipropionato de beclometasona", ["RENAME-2024"]),
    _entry("DISPOSITIVO_INTRAUTERINO_PLASTICO_COM_COBRE_DIU", "Dispositivo intrauterino plastico com cobre (DIU)", "Dispositivo intrauterino plastico com cobre (DIU)", ["RENAME-2024"]),
    _entry("DOLUTEGRAVIR_SODICO", "Dolutegravir sodico", "Dolutegravir sodico", ["RENAME-2024"]),
    _entry("DOLUTEGRAVIR_SODICO_MAIS_LAMIVUDINA", "Dolutegravir sodico + lamivudina", "Dolutegravir sodico + lamivudina", ["RENAME-2024"]),
    _entry("DOXICICLINA", "Doxiciclina", "Doxiciclina", ["RENAME-2024"]),
    _entry("ECULIZUMABE", "Eculizumabe", "Eculizumabe", ["RENAME-2024"]),
    _entry("EFAVIRENZ", "Efavirenz", "Efavirenz", ["RENAME-2024"]),
    _entry("ELBASVIR_MAIS_GRAZOPREVIR_MONIDRATADO", "Elbasvir + grazoprevir monidratado", "Elbasvir + grazoprevir monidratado", ["RENAME-2024"]),
    _entry("ELEXACAFTOR_TEZACAFTOR_IVACAFTOR_MAIS_IVACAFTOR", "Elexacaftor/tezacaftor/ ivacaftor + ivacaftor", "Elexacaftor/tezacaftor/ ivacaftor + ivacaftor", ["RENAME-2024"]),
    _entry("ELTROMBOPAGUE_OLAMINA", "Eltrombopague olamina", "Eltrombopague olamina", ["RENAME-2024"]),
    _entry("EMBONATO_DE_TRIPTORRELINA", "Embonato de triptorrelina", "Embonato de triptorrelina", ["RENAME-2024"]),
    _entry("EMICIZUMABE", "Emicizumabe", "Emicizumabe", ["RENAME-2024"]),
    _entry("EMPAGLIFLOZINA", "Empagliflozina", "Empagliflozina", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("ENALAPRIL", "Enalapril", "Enalapril", ["RENAME-2024"]),
    _entry("ENANTATO_DE_NORETISTERONA_MAIS_VALERATO_DE_ESTRADIOL", "Enantato de noretisterona + valerato de estradiol", "Enantato de noretisterona + valerato de estradiol", ["RENAME-2024"]),
    _entry("ENFUVIRTIDA", "Enfuvirtida", "Enfuvirtida", ["RENAME-2024"]),
    _entry("ENOXAPARINA", "Enoxaparina", "Enoxaparina sodica", ["RENAME-2024"]),
    _entry("ENTACAPONA", "Entacapona", "Entacapona", ["RENAME-2024"]),
    _entry("ENTECAVIR", "Entecavir", "Entecavir", ["RENAME-2024"]),
    _entry("EPINEFRINA", "Epinefrina", "Epinefrina", ["RENAME-2024"]),
    _entry("ESCITALOPRAM", "Escitalopram", "Escitalopram", ["RENAME-2024"]),
    _entry("ESPIRAMICINA", "Espiramicina", "Espiramicina", ["RENAME-2024"]),
    _entry("ESPIRONOLACTONA", "Espironolactona", "Espironolactona", ["RENAME-2024"]),
    _entry("ESTOLATO_DE_ERITROMICINA", "Estolato de eritromicina", "Estolato de eritromicina", ["RENAME-2024"]),
    _entry("ESTREPTOQUINASE", "Estreptoquinase", "Estreptoquinase", ["RENAME-2024"]),
    _entry("ESTRIOL", "Estriol", "Estriol", ["RENAME-2024"]),
    _entry("ESTROGENIOS_CONJUGADOS", "Estrogenios conjugados", "Estrogenios conjugados", ["RENAME-2024"]),
    _entry("ETANERCEPTE", "Etanercepte", "Etanercepte", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("ETINILESTRADIOL_MAIS_LEVONORGESTREL", "Etinilestradiol + levonorgestrel", "Etinilestradiol + levonorgestrel", ["RENAME-2024"]),
    _entry("ETIONAMIDA", "Etionamida", "Etionamida", ["RENAME-2024"]),
    _entry("ETOFIBRATO", "Etofibrato", "Etofibrato", ["RENAME-2024"]),
    _entry("ETOSSUXIMIDA", "Etossuximida", "Etossuximida", ["RENAME-2024"]),
    _entry("ETRAVIRINA", "Etravirina", "Etravirina", ["RENAME-2024"]),
    _entry("EVEROLIMO", "Everolimo", "Everolimo", ["RENAME-2024"]),
    _entry("FATOR_IX_DE_COAGULACAO", "Fator IX de coagulacao", "Fator IX de coagulacao", ["RENAME-2024"]),
    _entry("FATOR_VII_DE_COAGULACAO_ATIVADO_RECOMBINANTE", "Fator VII de coagulacao ativado recombinante", "Fator VII de coagulacao ativado recombinante", ["RENAME-2024"]),
    _entry("FATOR_VIII_DE_COAGULACAO", "Fator VIII de coagulacao", "Fator VIII de coagulacao", ["RENAME-2024"]),
    _entry("FATOR_VIII_DE_COAGULACAO_CONTENDO_FATOR_DE_VON_WILLEBRAND", "Fator VIII de coagulacao contendo fator de von Willebrand", "Fator VIII de coagulacao contendo fator de von Willebrand", ["RENAME-2024"]),
    _entry("FATOR_VIII_DE_COAGULACAO_RECOMBINANTE", "Fator VIII de coagulacao recombinante", "Fator VIII de coagulacao recombinante", ["RENAME-2024"]),
    _entry("FATOR_XIII_DE_COAGULACAO", "Fator XIII de coagulacao", "Fator XIII de coagulacao", ["RENAME-2024"]),
    _entry("FENITOINA", "Fenitoina", "Fenitoina", ["RENAME-2024"]),
    _entry("FENOBARBITAL", "Fenobarbital", "Fenobarbital", ["RENAME-2024"]),
    _entry("FENOFIBRATO", "Fenofibrato", "Fenofibrato", ["RENAME-2024"]),
    _entry("FENOXIMETILPENICILI_NA_POTASSICA", "Fenoximetilpenicili- na potassica", "Fenoximetilpenicili- na potassica", ["RENAME-2024"]),
    _entry("FERRIPOLIMALTOSE", "Ferripolimaltose", "Ferripolimaltose", ["RENAME-2024"]),
    _entry("FIBRINOGENIO", "Fibrinogenio", "Fibrinogenio", ["RENAME-2024"]),
    _entry("FILGRASTIM", "Filgrastim", "Filgrastim", ["RENAME-2024"]),
    _entry("FINASTERIDA", "Finasterida", "Finasterida", ["RENAME-2024"]),
    _entry("FLUCITOSINA", "Flucitosina", "Flucitosina", ["RENAME-2024"]),
    _entry("FLUCONAZOL", "Fluconazol", "Fluconazol", ["RENAME-2024"]),
    _entry("FLUMAZENIL", "Flumazenil", "Flumazenil", ["RENAME-2024"]),
    _entry("FLUOXETINA", "Fluoxetina", "Fluoxetina", ["RENAME-2024"]),
    _entry("FOLINATO_DE_CALCIO", "Folinato de calcio", "Folinato de calcio", ["RENAME-2024"]),
    _entry("FOSAMPRENAVIR", "Fosamprenavir", "Fosamprenavir", ["RENAME-2024"]),
    _entry("FOSFATO_DE_CALCIO_TRIBASICO_MAIS_COLECALCIFEROL", "Fosfato de calcio tribasico + colecalciferol", "Fosfato de calcio tribasico + colecalciferol", ["RENAME-2024"]),
    _entry("FOSFATO_DE_CLINDAMICINA", "Fosfato de clindamicina", "Fosfato de clindamicina", ["RENAME-2024"]),
    _entry("FOSFATO_DE_CODEINA", "Fosfato de codeina", "Fosfato de codeina", ["RENAME-2024"]),
    _entry("FOSFATO_DE_OSELTAMIVIR", "Fosfato de oseltamivir", "Fosfato de oseltamivir", ["RENAME-2024"]),
    _entry("FOSFATO_DE_POTASSIO_MONOBASICO_MAIS_FOSFATO_DE_POTASSIO_DIBASICO", "Fosfato de potassio monobasico + fosfato de potassio dibasico", "Fosfato de potassio monobasico + fosfato de potassio dibasico", ["RENAME-2024"]),
    _entry("FOSFATO_SODICO_DE_PREDNISOLONA", "Fosfato sodico de prednisolona", "Fosfato sodico de prednisolona", ["RENAME-2024"]),
    _entry("FOSTENSAVIR_TROMETAMOL", "Fostensavir trometamol", "Fostensavir trometamol", ["RENAME-2024"]),
    _entry("FUMARATO_DE_DIMETILA", "Fumarato de dimetila", "Fumarato de dimetila", ["RENAME-2024"]),
    _entry("FUMARATO_DE_FORMOTEROL", "Fumarato de formoterol", "Fumarato de formoterol", ["RENAME-2024"]),
    _entry("FUMARATO_DE_FORMOTEROL_MAIS_BUDESONIDA", "Fumarato de formoterol + budesonida", "Fumarato de formoterol + budesonida", ["RENAME-2024"]),
    _entry("FUMARATO_DE_TENOFOVIR_DESOPROXILA", "Fumarato de tenofovir desoproxila", "Fumarato de tenofovir desoproxila", ["RENAME-2024"]),
    _entry("FUMARATO_DE_TENOFOVIR_DESOPROXILA_MAIS_ENTRICITABINA", "Fumarato de tenofovir desoproxila + entricitabina", "Fumarato de tenofovir desoproxila + entricitabina", ["RENAME-2024"]),
    _entry("FUMARATO_DE_TENOFOVIR_DESOPROXILA_MAIS_LAMIVUDINA", "Fumarato de tenofovir desoproxila + lamivudina", "Fumarato de tenofovir desoproxila + lamivudina", ["RENAME-2024"]),
    _entry("FUMARATO_DE_TENOFOVIR_DESOPROXILA_MAIS_LAMIVUDINA_MAIS_EFAVIRENZ", "Fumarato de tenofovir desoproxila + lamivudina + efavirenz", "Fumarato de tenofovir desoproxila + lamivudina + efavirenz", ["RENAME-2024"]),
    _entry("FUROSEMIDA", "Furosemida", "Furosemida", ["RENAME-2024"]),
    _entry("GABAPENTINA", "Gabapentina", "Gabapentina", ["RENAME-2024"]),
    _entry("GALSULFASE", "Galsulfase", "Galsulfase", ["RENAME-2024"]),
    _entry("GENFIBROZILA", "Genfibrozila", "Genfibrozila", ["RENAME-2024"]),
    _entry("GENTAMICINA", "Gentamicina", "Gentamicina", ["RENAME-2024"]),
    _entry("GLECAPREVIR_MAIS_PIBRENTASVIR", "Glecaprevir + pibrentasvir", "Glecaprevir + pibrentasvir", ["RENAME-2024"]),
    _entry("GLIBENCLAMIDA", "Glibenclamida", "Glibenclamida", ["RENAME-2024"]),
    _entry("GLICEROL", "Glicerol", "Glicerol", ["RENAME-2024"]),
    _entry("GLICLAZIDA", "Gliclazida", "Gliclazida", ["RENAME-2024"]),
    _entry("GLICOSE", "Glicose", "Glicose", ["RENAME-2024"]),
    _entry("GOLIMUMABE", "Golimumabe", "Golimumabe", ["RENAME-2024"]),
    _entry("HALOPERIDOL", "Haloperidol", "Haloperidol", ["RENAME-2024"]),
    _entry("HEMIFUMARATO_DE_QUETIAPINA", "Hemifumarato de quetiapina", "Hemifumarato de quetiapina", ["RENAME-2024"]),
    _entry("HEMIFUMARATO_DE_TENOFOVIR_ALAFENAMIDA", "Hemifumarato de tenofovir alafenamida", "Hemifumarato de tenofovir alafenamida", ["RENAME-2024"]),
    _entry("HEMITARTARATO_DE_NOREPINEFRINA", "Hemitartarato de norepinefrina", "Hemitartarato de norepinefrina", ["RENAME-2024"]),
    _entry("HEPARINA_NAO_FRACIONADA", "Heparina nao fracionada", "Heparina sodica", ["RENAME-2024"]),
    _entry("HIDRALAZINA", "Hidralazina", "Hidralazina", ["RENAME-2024"]),
    _entry("HIDROCLOROTIAZIDA", "Hidroclorotiazida", "Hidroclorotiazida", ["RENAME-2024"]),
    _entry("HIDROCORTISONA", "Hidrocortisona", "Hidrocortisona", ["RENAME-2024"]),
    _entry("HIDROXICLOROQUINA", "Hidroxicloroquina", "Hidroxicloroquina", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("HIDROXIDO_DE_ALUMINIO", "Hidroxido de aluminio", "Hidroxido de aluminio", ["RENAME-2024"]),
    _entry("HIDROXIUREIA", "Hidroxiureia", "Hidroxiureia", ["RENAME-2024"]),
    _entry("HIPROMELOSE", "Hipromelose", "Hipromelose", ["RENAME-2024"]),
    _entry("IBUPROFENO", "Ibuprofeno", "Ibuprofeno", ["RENAME-2024"]),
    _entry("IDURSULFASE", "Idursulfase", "Idursulfase", ["RENAME-2024"]),
    _entry("ILOPROSTA", "Iloprosta", "Iloprosta", ["RENAME-2024"]),
    _entry("IMIGLUCERASE", "Imiglucerase", "Imiglucerase", ["RENAME-2024"]),
    _entry("IMIQUIMODE", "Imiquimode", "Imiquimode", ["RENAME-2024"]),
    _entry("IMUNOGLOBULINA_ANTI_RHO_D", "Imunoglobulina anti-Rho (D)", "Imunoglobulina anti-Rho (D)", ["RENAME-2024"]),
    _entry("IMUNOGLOBULINA_ANTITETANICA", "Imunoglobulina antitetanica", "Imunoglobulina antitetanica", ["RENAME-2024"]),
    _entry("IMUNOGLOBULINA_ANTITIMOCITOS_HUMANOS_COELHO", "Imunoglobulina antitimocitos humanos (coelho)", "Imunoglobulina antitimocitos humanos (coelho)", ["RENAME-2024"]),
    _entry("IMUNOGLOBULINA_HUMANA", "Imunoglobulina humana", "Imunoglobulina humana", ["RENAME-2024"]),
    _entry("IMUNOGLOBULINA_HUMANA_ANTI_HEPATITE_B", "Imunoglobulina humana anti- -hepatite B", "Imunoglobulina humana anti- -hepatite B", ["RENAME-2024"]),
    _entry("IMUNOGLOBULINA_HUMANA_ANTIRRABICA", "Imunoglobulina humana antirrabica", "Imunoglobulina humana antirrabica", ["RENAME-2024"]),
    _entry("IMUNOGLOBULINA_HUMANA_ANTIVARICELA_ZOSTER", "Imunoglobulina humana antivaricela zoster", "Imunoglobulina humana antivaricela zoster", ["RENAME-2024"]),
    _entry("INFLIXIMABE", "Infliximabe", "Infliximabe", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("INSULINA_ANALOGA_DE_ACAO_PROLONGADA", "Insulina analoga de acao prolongada", "Insulina analoga de acao prolongada", ["RENAME-2024"]),
    _entry("INSULINA_ANALOGA_DE_ACAO_RAPIDA", "Insulina analoga de acao rapida", "Insulina analoga de acao rapida", ["RENAME-2024"]),
    _entry("INSULINA_NPH", "Insulina humana NPH", "Insulina humana NPH", ["RENAME-2024"]),
    _entry("INSULINA_REGULAR", "Insulina humana regular", "Insulina humana regular", ["RENAME-2024"]),
    _entry("IODETO_DE_POTASSIO", "Iodeto de potassio", "Iodeto de potassio", ["RENAME-2024"]),
    _entry("IODO_MAIS_IODETO_DE_POTASSIO", "Iodo + iodeto de potassio", "Iodo + iodeto de potassio", ["RENAME-2024"]),
    _entry("ISETIONATO_DE_PENTAMIDINA", "Isetionato de pentamidina", "Isetionato de pentamidina", ["RENAME-2024"]),
    _entry("ISONIAZIDA", "Isoniazida", "Isoniazida", ["RENAME-2024"]),
    _entry("ISOTRETINOINA", "Isotretinoina", "Isotretinoina", ["RENAME-2024"]),
    _entry("ITRACONAZOL", "Itraconazol", "Itraconazol", ["RENAME-2024"]),
    _entry("IVACAFTOR", "Ivacaftor", "Ivacaftor", ["RENAME-2024"]),
    _entry("IVERMECTINA", "Ivermectina", "Ivermectina", ["RENAME-2024"]),
    _entry("LACTATO_DE_BIPERIDENO", "Lactato de biperideno", "Lactato de biperideno", ["RENAME-2024"]),
    _entry("LACTULOSE", "Lactulose", "Lactulose", ["RENAME-2024"]),
    _entry("LAMIVUDINA", "Lamivudina", "Lamivudina", ["RENAME-2024"]),
    _entry("LAMOTRIGINA", "Lamotrigina", "Lamotrigina", ["RENAME-2024"]),
    _entry("LARONIDASE", "Laronidase", "Laronidase", ["RENAME-2024"]),
    _entry("LATANOPROSTA", "Latanoprosta", "Latanoprosta", ["RENAME-2024"]),
    _entry("LEDIPASVIR_MAIS_SOFOSBOVIR", "Ledipasvir + sofosbovir", "Ledipasvir + sofosbovir", ["RENAME-2024"]),
    _entry("LEFLUNOMIDA", "Leflunomida", "Leflunomida", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("LEVETIRACETAM", "Levetiracetam", "Levetiracetam", ["RENAME-2024"]),
    _entry("LEVODOPA_MAIS_BENSERAZIDA", "Levodopa + benserazida", "Levodopa + benserazida", ["RENAME-2024"]),
    _entry("LEVODOPA_MAIS_CARBIDOPA", "Levodopa + carbidopa", "Levodopa + carbidopa", ["RENAME-2024"]),
    _entry("LEVOFLOXACINO", "Levofloxacino", "Levofloxacino", ["RENAME-2024"]),
    _entry("LEVONORGESTREL", "Levonorgestrel", "Levonorgestrel", ["RENAME-2024"]),
    _entry("LEVOTIROXINA", "Levotiroxina sodica", "Levotiroxina sodica", ["RENAME-2024"]),
    _entry("LINEZOLIDA", "Linezolida", "Linezolida", ["RENAME-2024"]),
    _entry("LOPINAVIR_MAIS_RITONAVIR", "Lopinavir + ritonavir", "Lopinavir + ritonavir", ["RENAME-2024"]),
    _entry("LORATADINA", "Loratadina", "Loratadina", ["RENAME-2024"]),
    _entry("LOSARTANA", "Losartana", "Losartana potassica", ["RENAME-2024"]),
    _entry("MALEATO_DE_DEXCLORFENIRAMINA", "Maleato de dexclorfeniramina", "Maleato de dexclorfeniramina", ["RENAME-2024"]),
    _entry("MALEATO_DE_ENALAPRIL", "Maleato de enalapril", "Maleato de enalapril", ["RENAME-2024"]),
    _entry("MALEATO_DE_TIMOLOL", "Maleato de timolol", "Maleato de timolol", ["RENAME-2024"]),
    _entry("MARAVIROQUE", "Maraviroque", "Maraviroque", ["RENAME-2024"]),
    _entry("MEPOLIZUMABE", "Mepolizumabe", "Mepolizumabe", ["RENAME-2024"]),
    _entry("MESALAZINA", "Mesalazina", "Mesalazina", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("MESILATO_DE_DESFERROXAMINA", "Mesilato de desferroxamina", "Mesilato de desferroxamina", ["RENAME-2024"]),
    _entry("MESILATO_DE_DOXAZOSINA", "Mesilato de doxazosina", "Mesilato de doxazosina", ["RENAME-2024"]),
    _entry("MESILATO_DE_RASAGILINA", "Mesilato de rasagilina", "Mesilato de rasagilina", ["RENAME-2024"]),
    _entry("METFORMINA", "Metformina", "Metformina", ["RENAME-2024"]),
    _entry("METILDOPA", "Metildopa", "Metildopa", ["RENAME-2024"]),
    _entry("METILSULFATO_DE_PRALIDOXIMA", "Metilsulfato de pralidoxima", "Metilsulfato de pralidoxima", ["RENAME-2024"]),
    _entry("METOCLOPRAMIDA", "Metoclopramida", "Metoclopramida", ["RENAME-2024"]),
    _entry("METOPROLOL", "Metoprolol", "Metoprolol", ["RENAME-2024"]),
    _entry("METOTREXATO", "Metotrexato", "Metotrexato", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("METRONIDAZOL", "Metronidazol", "Metronidazol", ["RENAME-2024"]),
    _entry("MICOFENOLATO_DE_MOFETILA", "Micofenolato de mofetila", "Micofenolato de mofetila", ["RENAME-2024"]),
    _entry("MICOFENOLATO_DE_SODIO", "Micofenolato de sodio", "Micofenolato de sodio", ["RENAME-2024"]),
    _entry("MICRONUTRIENTES", "Micronutrientes", "Micronutrientes", ["RENAME-2024"]),
    _entry("MIDAZOLAM", "Midazolam", "Midazolam", ["RENAME-2024"]),
    _entry("MIGLUSTATE", "Miglustate", "Miglustate", ["RENAME-2024"]),
    _entry("MILTEFOSINA", "Miltefosina", "Miltefosina", ["RENAME-2024"]),
    _entry("MISOPROSTOL", "Misoprostol", "Misoprostol", ["RENAME-2024"]),
    _entry("MONONITRATO_DE_ISOSSORBIDA", "Mononitrato de isossorbida", "Mononitrato de isossorbida", ["RENAME-2024"]),
    _entry("MORFINA", "Morfina", "Morfina", ["RENAME-2024"]),
    _entry("NAPROXENO", "Naproxeno", "Naproxeno", ["RENAME-2024"]),
    _entry("NATALIZUMABE", "Natalizumabe", "Natalizumabe", ["RENAME-2024"]),
    _entry("NEVIRAPINA", "Nevirapina", "Nevirapina", ["RENAME-2024"]),
    _entry("NICOTINA", "Nicotina", "Nicotina", ["RENAME-2024"]),
    _entry("NIFEDIPINO", "Nifedipino", "Nifedipino", ["RENAME-2024"]),
    _entry("NIFURTIMOX", "Nifurtimox", "Nifurtimox", ["RENAME-2024"]),
    _entry("NIRMATRELVIR_MAIS_RITONAVIR", "Nirmatrelvir + ritonavir", "Nirmatrelvir + ritonavir", ["RENAME-2024"]),
    _entry("NISTATINA", "Nistatina", "Nistatina", ["RENAME-2024"]),
    _entry("NITRATO_DE_MICONAZOL", "Nitrato de miconazol", "Nitrato de miconazol", ["RENAME-2024"]),
    _entry("NITROFURANTOINA", "Nitrofurantoina", "Nitrofurantoina", ["RENAME-2024"]),
    _entry("NORETISTERONA", "Noretisterona", "Noretisterona", ["RENAME-2024"]),
    _entry("NUSINERSENA", "Nusinersena", "Nusinersena", ["RENAME-2024"]),
    _entry("OFLOXACINO", "Ofloxacino", "Ofloxacino", ["RENAME-2024"]),
    _entry("OLANZAPINA", "Olanzapina", "Olanzapina", ["RENAME-2024"]),
    _entry("OLEO_MINERAL", "Oleo mineral", "Oleo mineral", ["RENAME-2024"]),
    _entry("OMALIZUMABE", "Omalizumabe", "Omalizumabe", ["RENAME-2024"]),
    _entry("OMEPRAZOL", "Omeprazol", "Omeprazol", ["RENAME-2024"]),
    _entry("ONASEMNOGENO_ABEPARVOVEQUE", "Onasemnogeno abeparvoveque", "Onasemnogeno abeparvoveque", ["RENAME-2024"]),
    _entry("ONDANSETRONA", "Ondansetrona", "Ondansetrona", ["RENAME-2024"]),
    _entry("OSELTAMIVIR", "Oseltamivir", "Oseltamivir", ["RENAME-2024"]),
    _entry("PALIVIZUMABE", "Palivizumabe", "Palivizumabe", ["RENAME-2024"]),
    _entry("PALMITATO_DE_RETINOL", "Palmitato de retinol", "Palmitato de retinol", ["RENAME-2024"]),
    _entry("PAMIDRONATO_DISSODICO", "Pamidronato dissodico", "Pamidronato dissodico", ["RENAME-2024"]),
    _entry("PAMOATO_DE_PASIREOTIDA", "Pamoato de pasireotida", "Pamoato de pasireotida", ["RENAME-2024"]),
    _entry("PANCREATINA", "Pancreatina", "Pancreatina", ["RENAME-2024"]),
    _entry("PANTOPRAZOL", "Pantoprazol", "Pantoprazol", ["RENAME-2024"]),
    _entry("PARACETAMOL", "Paracetamol", "Paracetamol", ["RENAME-2024"]),
    _entry("PARICALCITOL", "Paricalcitol", "Paricalcitol", ["RENAME-2024"]),
    _entry("PASTA_DE_OXIDO_DE_ZINCO_FN", "Pasta de oxido de zinco (FN)", "Pasta de oxido de zinco (FN)", ["RENAME-2024"]),
    _entry("PENICILAMINA", "Penicilamina", "Penicilamina", ["RENAME-2024"]),
    _entry("PENTOXIFILINA", "Pentoxifilina", "Pentoxifilina", ["RENAME-2024"]),
    _entry("PERMANGANATO_DE_POTASSIO", "Permanganato de potassio", "Permanganato de potassio", ["RENAME-2024"]),
    _entry("PERMETRINA", "Permetrina", "Permetrina", ["RENAME-2024"]),
    _entry("PEROXIDO_DE_BENZOILA_FN", "Peroxido de benzoila (FN)", "Peroxido de benzoila (FN)", ["RENAME-2024"]),
    _entry("PIRAZINAMIDA", "Pirazinamida", "Pirazinamida", ["RENAME-2024"]),
    _entry("PIRIMETAMINA", "Pirimetamina", "Pirimetamina", ["RENAME-2024"]),
    _entry("PODOFILINA_FN", "Podofilina (FN)", "Podofilina (FN)", ["RENAME-2024"]),
    _entry("PODOFILOTOXINA", "Podofilotoxina", "Podofilotoxina", ["RENAME-2024"]),
    _entry("PRAVASTATINA_SODICA", "Pravastatina sodica", "Pravastatina sodica", ["RENAME-2024"]),
    _entry("PRAZIQUANTEL", "Praziquantel", "Praziquantel", ["RENAME-2024"]),
    _entry("PREDNISOLONA", "Prednisolona", "Prednisolona", ["RENAME-2024"]),
    _entry("PREDNISONA", "Prednisona", "Prednisona", ["RENAME-2024"]),
    _entry("PRETOMANIDA", "Pretomanida", "Pretomanida", ["RENAME-2024"]),
    _entry("PRIMIDONA", "Primidona", "Primidona", ["RENAME-2024"]),
    _entry("PROPILTIOURACILA", "Propiltiouracila", "Propiltiouracila", ["RENAME-2024"]),
    _entry("PROPIONATO_DE_CLOBETASOL", "Propionato de clobetasol", "Propionato de clobetasol", ["RENAME-2024"]),
    _entry("QUETIAPINA", "Quetiapina", "Quetiapina", ["RENAME-2024"]),
    _entry("RALTEGRAVIR_POTASSICO", "Raltegravir potassico", "Raltegravir potassico", ["RENAME-2024"]),
    _entry("RAVULIZUMABE", "Ravulizumabe", "Ravulizumabe", ["RENAME-2024"]),
    _entry("RIBAVIRINA", "Ribavirina", "Ribavirina", ["RENAME-2024"]),
    _entry("RIFABUTINA", "Rifabutina", "Rifabutina", ["RENAME-2024"]),
    _entry("RIFAMPICINA_MAIS_ISONIAZIDA", "Rifampicina + isoniazida", "Rifampicina + isoniazida", ["RENAME-2024"]),
    _entry("RIFAMPICINA_MAIS_ISONIAZIDA_MAIS_PIRAZINAMIDA", "Rifampicina + isoniazida + pirazinamida", "Rifampicina + isoniazida + pirazinamida", ["RENAME-2024"]),
    _entry("RIFAMPICINA_MAIS_ISONIAZIDA_MAIS_PIRAZINAMIDA_MAIS_CLORIDRATO_DE_ETAMBUTOL", "Rifampicina + isoniazida + pirazinamida + cloridrato de etambutol", "Rifampicina + isoniazida + pirazinamida + cloridrato de etambutol", ["RENAME-2024"]),
    _entry("RIFAPENTINA", "Rifapentina", "Rifapentina", ["RENAME-2024"]),
    _entry("RIFAPENTINA_MAIS_ISONIAZIDA", "Rifapentina + isoniazida", "Rifapentina + isoniazida", ["RENAME-2024"]),
    _entry("RILUZOL", "Riluzol", "Riluzol", ["RENAME-2024"]),
    _entry("RISANQUIZUMABE", "Risanquizumabe", "Risanquizumabe", ["RENAME-2024"]),
    _entry("RISDIPLAM", "Risdiplam", "Risdiplam", ["RENAME-2024"]),
    _entry("RISEDRONATO_SODICO", "Risedronato sodico", "Risedronato sodico", ["RENAME-2024"]),
    _entry("RISPERIDONA", "Risperidona", "Risperidona", ["RENAME-2024"]),
    _entry("RITONAVIR", "Ritonavir", "Ritonavir", ["RENAME-2024"]),
    _entry("RITUXIMABE", "Rituximabe", "Rituximabe", ["RENAME-2024"]),
    _entry("RIVASTIGMINA", "Rivastigmina", "Rivastigmina", ["RENAME-2024"]),
    _entry("ROMOSOZUMABE", "Romosozumabe", "Romosozumabe", ["RENAME-2024"]),
    _entry("SACARATO_DE_HIDROXIDO_FERRICO", "Sacarato de hidroxido ferrico", "Sacarato de hidroxido ferrico", ["RENAME-2024"]),
    _entry("SACUBITRIL_VALSARTANA_SODICA_HIDRATADA", "Sacubitril valsartana sodica hidratada", "Sacubitril valsartana sodica hidratada", ["RENAME-2024"]),
    _entry("SAIS_PARA_REIDRATACAO_ORAL", "Sais para reidratacao oral", "Sais para reidratacao oral", ["RENAME-2024"]),
    _entry("SALBUTAMOL", "Salbutamol", "Salbutamol", ["RENAME-2024"]),
    _entry("SECUQUINUMABE", "Secuquinumabe", "Secuquinumabe", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("SELEXIPAGUE", "Selexipague", "Selexipague", ["RENAME-2024"]),
    _entry("SERTRALINA", "Sertralina", "Sertralina", ["RENAME-2024"]),
    _entry("SINVASTATINA", "Sinvastatina", "Sinvastatina", ["RENAME-2024"]),
    _entry("SIROLIMO", "Sirolimo", "Sirolimo", ["RENAME-2024"]),
    _entry("SOFOSBUVIR", "Sofosbuvir", "Sofosbuvir", ["RENAME-2024"]),
    _entry("SOFOSBUVIR_MAIS_VELPATASVIR", "Sofosbuvir + velpatasvir", "Sofosbuvir + velpatasvir", ["RENAME-2024"]),
    _entry("SOFOSBUVIR_MAIS_VELPATASVIR_MAIS_VOXILAPREVIR", "Sofosbuvir + velpatasvir + voxilaprevir", "Sofosbuvir + velpatasvir + voxilaprevir", ["RENAME-2024"]),
    _entry("SOLUCAO_RINGER_MAIS_LACTATO", "Solucao ringer + lactato", "Solucao ringer + lactato", ["RENAME-2024"]),
    _entry("SOMATROPINA", "Somatropina", "Somatropina", ["RENAME-2024"]),
    _entry("SORO_ANTIARACNIDICO_LOXOSCELES_PHONEUTRIA_E_TITYUS", "Soro antiaracnidico (Loxosceles, Phoneutria e Tityus)", "Soro antiaracnidico (Loxosceles, Phoneutria e Tityus)", ["RENAME-2024"]),
    _entry("SORO_ANTIBOTROPICO_PENTAVALENTE", "Soro antibotropico (pentavalente)", "Soro antibotropico (pentavalente)", ["RENAME-2024"]),
    _entry("SORO_ANTIBOTROPICO_PENTAVALENTE_E_ANTICROTALICO", "Soro antibotropico (pentavalente) e anticrotalico", "Soro antibotropico (pentavalente) e anticrotalico", ["RENAME-2024"]),
    _entry("SORO_ANTIBOTROPICO_PENTAVALENTE_E_ANTILAQUETICO", "Soro antibotropico (pentavalente) e antilaquetico", "Soro antibotropico (pentavalente) e antilaquetico", ["RENAME-2024"]),
    _entry("SORO_ANTIBOTULINICO_AB_BIVALENTE", "Soro antibotulinico AB (bivalente)", "Soro antibotulinico AB (bivalente)", ["RENAME-2024"]),
    _entry("SORO_ANTICROTALICO", "Soro anticrotalico", "Soro anticrotalico", ["RENAME-2024"]),
    _entry("SORO_ANTIDIFTERICO", "Soro antidifterico", "Soro antidifterico", ["RENAME-2024"]),
    _entry("SORO_ANTIELAPIDICO_BIVALENTE", "Soro antielapidico (bivalente)", "Soro antielapidico (bivalente)", ["RENAME-2024"]),
    _entry("SORO_ANTIESCORPIONICO", "Soro antiescorpionico", "Soro antiescorpionico", ["RENAME-2024"]),
    _entry("SORO_ANTILONOMICO", "Soro antilonomico", "Soro antilonomico", ["RENAME-2024"]),
    _entry("SORO_ANTILOXOSCELICO_TRIVALENTE", "Soro antiloxoscelico (trivalente)", "Soro antiloxoscelico (trivalente)", ["RENAME-2024"]),
    _entry("SORO_ANTIRRABICO", "Soro antirrabico", "Soro antirrabico", ["RENAME-2024"]),
    _entry("SORO_ANTITETANICO", "Soro antitetanico", "Soro antitetanico", ["RENAME-2024"]),
    _entry("SUCCINATO_DE_METOPROLOL", "Succinato de metoprolol", "Succinato de metoprolol", ["RENAME-2024"]),
    _entry("SUCCINATO_DE_TAFENOQUINA", "Succinato de tafenoquina", "Succinato de tafenoquina", ["RENAME-2024"]),
    _entry("SUCCINATO_SODICO_DE_HIDROCORTISONA", "Succinato sodico de hidrocortisona", "Succinato sodico de hidrocortisona", ["RENAME-2024"]),
    _entry("SUCCINATO_SODICO_DE_METILPREDNISOLONA", "Succinato sodico de metilprednisolona", "Succinato sodico de metilprednisolona", ["RENAME-2024"]),
    _entry("SULFADIAZINA", "Sulfadiazina", "Sulfadiazina", ["RENAME-2024"]),
    _entry("SULFADIAZINA_DE_PRATA", "Sulfadiazina de prata", "Sulfadiazina de prata", ["RENAME-2024"]),
    _entry("SULFAMETOXAZOL_TRIMETOPRIMA", "Sulfametoxazol + trimetoprima", "Sulfametoxazol + trimetoprima", ["RENAME-2024"]),
    _entry("SULFASSALAZINA", "Sulfassalazina", "Sulfassalazina", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("SULFATO_DE_ABACAVIR", "Sulfato de abacavir", "Sulfato de abacavir", ["RENAME-2024"]),
    _entry("SULFATO_DE_AMICACINA", "Sulfato de amicacina", "Sulfato de amicacina", ["RENAME-2024"]),
    _entry("SULFATO_DE_ATAZANAVIR", "Sulfato de atazanavir", "Sulfato de atazanavir", ["RENAME-2024"]),
    _entry("SULFATO_DE_ATROPINA", "Sulfato de atropina", "Sulfato de atropina", ["RENAME-2024"]),
    _entry("SULFATO_DE_ESTREPTOMICINA", "Sulfato de estreptomicina", "Sulfato de estreptomicina", ["RENAME-2024"]),
    _entry("SULFATO_DE_GENTAMICINA", "Sulfato de gentamicina", "Sulfato de gentamicina", ["RENAME-2024"]),
    _entry("SULFATO_DE_HIDROXICLOROQUINA", "Sulfato de hidroxicloroquina", "Sulfato de hidroxicloroquina", ["RENAME-2024"]),
    _entry("SULFATO_DE_ISAVUCONAZONIO", "Sulfato de Isavuconazonio", "Sulfato de Isavuconazonio", ["RENAME-2024"]),
    _entry("SULFATO_DE_MAGNESIO", "Sulfato de magnesio", "Sulfato de magnesio", ["RENAME-2024"]),
    _entry("SULFATO_DE_MORFINA", "Sulfato de morfina", "Sulfato de morfina", ["RENAME-2024"]),
    _entry("SULFATO_DE_POLIMIXINA_B_MAIS_SULFATO_DE_NEOMICINA_MAIS_FLUOCINOLONA_ACETONIDA_MAIS_CLORIDRATO_DE_LIDOCAINA", "Sulfato de polimixina B + sulfato de neomicina + fluocinolona acetonida + cloridrato de lidocaina", "Sulfato de polimixina B + sulfato de neomicina + fluocinolona acetonida + cloridrato de lidocaina", ["RENAME-2024"]),
    _entry("SULFATO_DE_SALBUTAMOL", "Sulfato de salbutamol", "Sulfato de salbutamol", ["RENAME-2024"]),
    _entry("SULFATO_DE_ZINCO", "Sulfato de zinco", "Sulfato de zinco", ["RENAME-2024"]),
    _entry("SULFATO_FERROSO", "Sulfato ferroso", "Sulfato ferroso", ["RENAME-2024"]),
    _entry("TACROLIMO", "Tacrolimo", "Tacrolimo", ["RENAME-2024"]),
    _entry("TAFAMIDIS", "Tafamidis", "Tafamidis", ["RENAME-2024"]),
    _entry("TAFAMIDIS_MEGLUMINA", "Tafamidis meglumina", "Tafamidis meglumina", ["RENAME-2024"]),
    _entry("TALIDOMIDA", "Talidomida", "Talidomida", ["RENAME-2024"]),
    _entry("TARTARATO_DE_BRIMONIDINA", "Tartarato de brimonidina", "Tartarato de brimonidina", ["RENAME-2024"]),
    _entry("TARTARATO_DE_METOPROLOL", "Tartarato de metoprolol", "Tartarato de metoprolol", ["RENAME-2024"]),
    _entry("TECLOZANA", "Teclozana", "Teclozana", ["RENAME-2024"]),
    _entry("TENECTEPLASE", "Tenecteplase", "Tenecteplase", ["RENAME-2024"]),
    _entry("TERIFLUNOMIDA", "Teriflunomida", "Teriflunomida", ["RENAME-2024"]),
    _entry("TERIZIDONA", "Terizidona", "Terizidona", ["RENAME-2024"]),
    _entry("TIAMAZOL", "Tiamazol", "Tiamazol", ["RENAME-2024"]),
    _entry("TIPRANAVIR", "Tipranavir", "Tipranavir", ["RENAME-2024"]),
    _entry("TOBRAMICINA", "Tobramicina", "Tobramicina", ["RENAME-2024"]),
    _entry("TOCILIZUMABE", "Tocilizumabe", "Tocilizumabe", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("TOFACITINIBE", "Tofacitinibe", "Tofacitinibe", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("TOPIRAMATO", "Topiramato", "Topiramato", ["RENAME-2024"]),
    _entry("TOXINA_BOTULINICA_A", "Toxina botulinica A", "Toxina botulinica A", ["RENAME-2024"]),
    _entry("TRAMADOL", "Tramadol", "Tramadol", ["RENAME-2024"]),
    _entry("TRAVOPROSTA", "Travoprosta", "Travoprosta", ["RENAME-2024"]),
    _entry("TRIPTORRELINA", "Triptorrelina", "Triptorrelina", ["RENAME-2024"]),
    _entry("UPADACITINIBE", "Upadacitinibe", "Upadacitinibe", ["RENAME-2024"]),
    _entry("USTEQUINUMABE", "Ustequinumabe", "Ustequinumabe", ["CONITEC-PCDT", "RENAME-2024"]),
    _entry("VACINA_ADSORVIDA_DIFTERIA_E_TETANO_ADULTO", "Vacina adsorvida difteria e tetano adulto", "Vacina adsorvida difteria e tetano adulto", ["RENAME-2024"]),
    _entry("VACINA_ADSORVIDA_DIFTERIA_E_TETANO_INFANTIL", "Vacina adsorvida difteria e tetano infantil", "Vacina adsorvida difteria e tetano infantil", ["RENAME-2024"]),
    _entry("VACINA_ADSORVIDA_DIFTERIA_TETANO_E_PERTUSSIS", "Vacina adsorvida difteria, tetano e pertussis", "Vacina adsorvida difteria, tetano e pertussis", ["RENAME-2024"]),
    _entry("VACINA_ADSORVIDA_DIFTERIA_TETANO_E_PERTUSSIS_ACELULAR_ADULTO", "Vacina adsorvida difteria, tetano e pertussis (acelular) adulto", "Vacina adsorvida difteria, tetano e pertussis (acelular) adulto", ["RENAME-2024"]),
    _entry("VACINA_ADSORVIDA_DIFTERIA_TETANO_E_PERTUSSIS_ACELULAR_INFANTIL", "Vacina adsorvida difteria, tetano e pertussis (acelular) infantil", "Vacina adsorvida difteria, tetano e pertussis (acelular) infantil", ["RENAME-2024"]),
    _entry("VACINA_ADSORVIDA_DIFTERIA_TETANO_PERTUSSIS_HEPATITE_B_RECOMBINANTE_E_HAEMOPHILUS_INFLUENZAE_B_CONJUGADA", "Vacina adsorvida difteria, tetano, pertussis, hepatite B (recombinante) e Haemophilus influenzae B (conjugada)", "Vacina adsorvida difteria, tetano, pertussis, hepatite B (recombinante) e Haemophilus influenzae B (conjugada)", ["RENAME-2024"]),
    _entry("VACINA_ADSORVIDA_HEPATITE_A_INATIVADA_ADULTO", "Vacina adsorvida hepatite A (inativada) adulto", "Vacina adsorvida hepatite A (inativada) adulto", ["RENAME-2024"]),
    _entry("VACINA_ADSORVIDA_HEPATITE_A_INATIVADA_INFANTIL", "Vacina adsorvida hepatite A (inativada) infantil", "Vacina adsorvida hepatite A (inativada) infantil", ["RENAME-2024"]),
    _entry("VACINA_BCG", "Vacina BCG", "Vacina BCG", ["RENAME-2024"]),
    _entry("VACINA_COLERA_INATIVADA", "Vacina colera (inativada)", "Vacina colera (inativada)", ["RENAME-2024"]),
    _entry("VACINA_FEBRE_AMARELA_ATENUADA", "Vacina febre amarela (atenuada)", "Vacina febre amarela (atenuada)", ["RENAME-2024"]),
    _entry("VACINA_FEBRE_TIFOIDE_POLISSACARIDICA", "Vacina febre tifoide (polissacaridica)", "Vacina febre tifoide (polissacaridica)", ["RENAME-2024"]),
    _entry("VACINA_HAEMOPHILUS_INFLUENZAE_B_CONJUGADA", "Vacina Haemophilus influenzae B (conjugada)", "Vacina Haemophilus influenzae B (conjugada)", ["RENAME-2024"]),
    _entry("VACINA_HEPATITE_B_RECOMBINANTE", "Vacina hepatite B (recombinante)", "Vacina hepatite B (recombinante)", ["RENAME-2024"]),
    _entry("VACINA_INFLUENZA_TRIVALENTE_FRAGMENTADA_INATIVADA", "Vacina influenza trivalente (fragmentada, inativada)", "Vacina influenza trivalente (fragmentada, inativada)", ["RENAME-2024"]),
    _entry("VACINA_MENINGOCOCICA_ACWY_CONJUGADA", "Vacina meningococica ACWY (conjugada)", "Vacina meningococica ACWY (conjugada)", ["RENAME-2024"]),
    _entry("VACINA_MENINGOCOCICA_C_CONJUGADA", "Vacina meningococica C (conjugada)", "Vacina meningococica C (conjugada)", ["RENAME-2024"]),
    _entry("VACINA_PAPILOMAVIRUS_HUMANO_6_11_16_E_18_RECOMBINANTE", "Vacina papilomavirus humano 6, 11, 16 e 18 (recombinante)", "Vacina papilomavirus humano 6, 11, 16 e 18 (recombinante)", ["RENAME-2024"]),
    _entry("VACINA_PNEUMOCOCICA_10_VALENTE_CONJUGADA", "Vacina pneumococica 10-valente (conjugada)", "Vacina pneumococica 10-valente (conjugada)", ["RENAME-2024"]),
    _entry("VACINA_PNEUMOCOCICA_13_VALENTE_CONJUGADA", "Vacina pneumococica 13-valente (conjugada)", "Vacina pneumococica 13-valente (conjugada)", ["RENAME-2024"]),
    _entry("VACINA_PNEUMOCOCICA_23_VALENTE_POLISSACARIDICA", "Vacina pneumococica 23-valente (polissacaridica)", "Vacina pneumococica 23-valente (polissacaridica)", ["RENAME-2024"]),
    _entry("VACINA_POLIOMIELITE_1_E_3_ATENUADA", "Vacina poliomielite 1 e 3 (atenuada)", "Vacina poliomielite 1 e 3 (atenuada)", ["RENAME-2024"]),
    _entry("VACINA_POLIOMIELITE_1_2_E_3_INATIVADA", "Vacina poliomielite 1, 2 e 3 (inativada)", "Vacina poliomielite 1, 2 e 3 (inativada)", ["RENAME-2024"]),
    _entry("VACINA_RAIVA_INATIVADA", "Vacina raiva (inativada)", "Vacina raiva (inativada)", ["RENAME-2024"]),
    _entry("VACINA_ROTAVIRUS_HUMANO_G1P_8_ATENUADA", "Vacina rotavirus humano G1P [8] (atenuada)", "Vacina rotavirus humano G1P [8] (atenuada)", ["RENAME-2024"]),
    _entry("VACINA_SARAMPO_CAXUMBA_RUBEOLA", "Vacina sarampo, caxumba, rubeola", "Vacina sarampo, caxumba, rubeola", ["RENAME-2024"]),
    _entry("VACINA_SARAMPO_CAXUMBA_RUBEOLA_E_VARICELA_ATENUADA", "Vacina sarampo, caxumba, rubeola e varicela (atenuada)", "Vacina sarampo, caxumba, rubeola e varicela (atenuada)", ["RENAME-2024"]),
    _entry("VACINA_VARICELA_ATENUADA", "Vacina varicela (atenuada)", "Vacina varicela (atenuada)", ["RENAME-2024"]),
    _entry("VALPROATO_DE_SODIO", "Valproato de sodio", "Valproato de sodio", ["RENAME-2024"]),
    _entry("VARFARINA", "Varfarina", "Varfarina sodica", ["RENAME-2024"]),
    _entry("VEDOLIZUMABE", "Vedolizumabe", "Vedolizumabe", ["RENAME-2024"]),
    _entry("VIGABATRINA", "Vigabatrina", "Vigabatrina", ["RENAME-2024"]),
    _entry("VORICONAZOL", "Voriconazol", "Voriconazol", ["RENAME-2024"]),
    _entry("XINAFOATO_DE_SALMETEROL", "Xinafoato de salmeterol", "Xinafoato de salmeterol", ["RENAME-2024"]),
    _entry("ZANAMIVIR", "Zanamivir", "Zanamivir", ["RENAME-2024"]),
    _entry("ZIDOVUDINA", "Zidovudina", "Zidovudina", ["RENAME-2024"]),
    _entry("ZIDOVUDINA_MAIS_LAMIVUDINA", "Zidovudina + lamivudina", "Zidovudina + lamivudina", ["RENAME-2024"]),
]

MEDICATION_LIST: list[MedicationOption] = sorted(
    _MEDICATIONS,
    key=lambda med: med.label.lower(),
)


def list_medications() -> list[MedicationOption]:
    return MEDICATION_LIST
