"""Add alerts table

Revision ID: 9fc83ede69ff
Revises: 20260417_1300
Create Date: 2026-04-17 16:46:56.561354

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9fc83ede69ff'
down_revision = '20260417_1300'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('patient_id', sa.String(), nullable=False),
    sa.Column('severity', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=False),
    sa.Column('message', sa.String(), nullable=False),
    sa.Column('team', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('resolved', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alerts_created_at'), 'alerts', ['created_at'], unique=False)
    op.create_index(op.f('ix_alerts_patient_id'), 'alerts', ['patient_id'], unique=False)
    op.create_index(op.f('ix_alerts_resolved'), 'alerts', ['resolved'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_resolved'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_patient_id'), table_name='alerts')
    op.drop_index(op.f('ix_alerts_created_at'), table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
